### ISSUE TITLE
Test execution order incorrect if test suite contains a mix of test cases and test suites

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#7]
While trying to work around the lack of pre/post execution script logs (Issue #6), we created a master Test Suite that contained an initialization TC, to substitute for the pre-execution script, a couple of test suites with TCs, and a teardown TC, to substitute for the post-execution script.
When run, the initialization and teardown TCs were executed first, then the test suites.  As seen in the screenshot below.

![execution](https://f.cloud.github.com/assets/3911048/502313/89287bf8-bcac-11e2-89db-6d148a5c4400.jpeg)

We expected the tests in each test suite to run in the order specified.

This was run from the most recent Twister version from GitHub.

**Comment by bogdanpopescu** [comment]
Fixed with the submission on 17th May ( Rlease_2.002 tag )

**Comment by bogdanpopescu** [comment]
@CJHoffmann  Please verify it

**Comment by CJHoffmann** [comment]
The issue still persists with the latest load.  In the image you can see the order the test suites and test cases were placed and in the log window the order in which the test cases were executed.
![testsequence_fail](https://f.cloud.github.com/assets/3911048/519371/3ced3966-bf15-11e2-870f-1df58cb8d7b9.jpg)

**Comment by croqaz** [comment]
Confirmed. A bug fix is in work.

**Comment by bogdanpopescu** [comment]
Provided fix in tag 31_05_2013.
@CJHoffmann  please verify it.

**Comment by sandhyamisra** [comment]
This has been verified and works fine. Can be closed.
